"""sync_models

Revision ID: fb53bdfe7210
Revises: fceaa7b7c2e9
Create Date: 2026-05-28 08:26:52.241129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb53bdfe7210'
down_revision: Union[str, Sequence[str], None] = 'fceaa7b7c2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_sessions', sa.Column('current_phase', sa.String(length=20), nullable=False, server_default='MORNING_COSTING'))
    op.add_column('daily_sessions', sa.Column('total_spending', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('daily_sessions', sa.Column('used_capital', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('daily_sessions', sa.Column('cogs_per_unit', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('daily_sessions', sa.Column('total_revenue', sa.Integer(), nullable=True))
    op.add_column('daily_sessions', sa.Column('net_profit', sa.Integer(), nullable=True))
    op.add_column('daily_sessions', sa.Column('portions_sold', sa.Integer(), nullable=True))
    op.add_column('daily_sessions', sa.Column('selling_price', sa.Integer(), nullable=True))
    op.add_column('daily_sessions', sa.Column('break_even', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('daily_sessions_user_id_fkey'), 'daily_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'daily_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('daily_sessions', 'total_belanja')
    op.drop_column('daily_sessions', 'laba_bersih')
    op.drop_column('daily_sessions', 'balik_modal')
    op.drop_column('daily_sessions', 'fase_saat_ini')
    op.drop_column('daily_sessions', 'modal_terpakai')
    op.drop_column('daily_sessions', 'porsi_terjual')
    op.drop_column('daily_sessions', 'hpp_unit')
    op.drop_column('daily_sessions', 'total_pendapatan')
    op.drop_column('daily_sessions', 'harga_jual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_sessions', sa.Column('harga_jual', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('daily_sessions', sa.Column('total_pendapatan', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('daily_sessions', sa.Column('hpp_unit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_sessions', sa.Column('porsi_terjual', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('daily_sessions', sa.Column('modal_terpakai', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('daily_sessions', sa.Column('fase_saat_ini', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('daily_sessions', sa.Column('balik_modal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('daily_sessions', sa.Column('laba_bersih', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('daily_sessions', sa.Column('total_belanja', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'daily_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('daily_sessions_user_id_fkey'), 'daily_sessions', 'users', ['user_id'], ['id'])
    op.drop_column('daily_sessions', 'break_even')
    op.drop_column('daily_sessions', 'selling_price')
    op.drop_column('daily_sessions', 'portions_sold')
    op.drop_column('daily_sessions', 'net_profit')
    op.drop_column('daily_sessions', 'total_revenue')
    op.drop_column('daily_sessions', 'cogs_per_unit')
    op.drop_column('daily_sessions', 'used_capital')
    op.drop_column('daily_sessions', 'total_spending')
    op.drop_column('daily_sessions', 'current_phase')
    # ### end Alembic commands ###
